### ISSUE TITLE
KeyError in Google Storage backend

### ISSUE THREAD

**Issue by dgilman** [s3ql/s3ql#121]
A KeyError was thrown while s3ql was running overnight. Lots of data was being written at the time. I'm on Debian Stable in python 3.7 environment and s3ql 3.1.

```
Sep 03 13:21:57 serverus mount.s3ql[10170]: Requesting new access token
Sep 03 13:21:59 serverus mount.s3ql[10170]: Uncaught top-level exception:
Sep 03 13:21:59 serverus mount.s3ql[10170]: Traceback (most recent call last):
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
Sep 03 13:21:59 serverus mount.s3ql[10170]:     return method(*a, **kw)
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/gs.py", line 443, in write_fh
Sep 03 13:21:59 serverus mount.s3ql[10170]:     raise AccessTokenExpired()
Sep 03 13:21:59 serverus mount.s3ql[10170]: s3ql.backends.gs.AccessTokenExpired
Sep 03 13:21:59 serverus mount.s3ql[10170]: During handling of the above exception, another exception occurred:
Sep 03 13:21:59 serverus mount.s3ql[10170]: Traceback (most recent call last):
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/mount.py", line 58, in run_with_except_hook
Sep 03 13:21:59 serverus mount.s3ql[10170]:     run_old(*args, **kw)
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Sep 03 13:21:59 serverus mount.s3ql[10170]:     self._target(*self._args, **self._kwargs)
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/block_cache.py", line 446, in _upload_loop
Sep 03 13:21:59 serverus mount.s3ql[10170]:     self._do_upload(*tmp)
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/block_cache.py", line 473, in _do_upload
Sep 03 13:21:59 serverus mount.s3ql[10170]:     % obj_id).get_obj_size()
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
Sep 03 13:21:59 serverus mount.s3ql[10170]:     return method(*a, **kw)
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 279, in perform_write
Sep 03 13:21:59 serverus mount.s3ql[10170]:     return fn(fh)
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/comprenc.py", line 389, in __exit__
Sep 03 13:21:59 serverus mount.s3ql[10170]:     self.close()
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/comprenc.py", line 383, in close
Sep 03 13:21:59 serverus mount.s3ql[10170]:     self.fh.close()
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/comprenc.py", line 548, in close
Sep 03 13:21:59 serverus mount.s3ql[10170]:     self.fh.close()
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/gs.py", line 893, in close
Sep 03 13:21:59 serverus mount.s3ql[10170]:     self.metadata, size=self.obj_size)
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 112, in wrapped
Sep 03 13:21:59 serverus mount.s3ql[10170]:     if not self.is_temp_failure(exc):
Sep 03 13:21:59 serverus mount.s3ql[10170]:   File "/home/user/s3ql/s3ql-3.1/venv/lib/python3.7/site-packages/s3ql-3.1-py3.7-linux-x86_64.egg/s3ql/backends/gs.py", line 212, in is_temp_failure
Sep 03 13:21:59 serverus mount.s3ql[10170]:     del self.access_token[self.refresh_token]
Sep 03 13:21:59 serverus mount.s3ql[10170]: KeyError: 'foobar'
Sep 03 13:21:59 serverus mount.s3ql[10170]: Requesting new access token
```

After the 13:21:59 "Requesting new access token" message there were no exceptions and the "Requesting new access token" messages kept appearing in the logs for a few hours.

So the first issue here is that exception above - was that gracefully handled, or was there a fatal error?

The second issue is that I came back the next day, saw the error and decided to unmount the file system. I have it mounted with systemd and it hit the 42 second timeout in the unit file, causing systemd to kill s3ql and forcing a bad fsck.  At the time of the systemd killing the heavy i/o was over and s3ql had plenty of time to flush data to disk.  Do you think the hang was related to the above error? Or maybe things were still flushing as part of the unmount and it took more than the timeout to write everything out.

**Comment by dgilman** [comment]
I should add that this was a single, large file, multiple gigabytes in size and was being slowly written into the s3ql mount for a few hours at the time this all went down.

I'm also not 100% sure but I think this file copy had been abruptly cancelled by an i/o error elsewhere causing the writing process to terminate. I say I'm not 100% sure because I don't have the timestamps to establish if s3ql errored first or if this did.

**Comment by return999** [comment]
Happens to me as well with a backup to Google Cloud. Tried with both oauth2 and ADC, both failed in the middle of a large backup with key expiration-related messages. I'm using version 3.3 / Python 3.6.8. It didn't fail in the middle of transferring a large file, it was a pretty small file when it crashed.

I saw activity related to this bug in March, thought it would have been fixed, but apparently not yet.

Thanks for any help on this, until it's fixed I can't back up. This used to be pretty reliable for me, didn't get this sort of errors and I've been using s3ql for years.

And now I don't even know what I'm supposed to do: can I continue the backup, or should I assume there's creeping corruption in the filesystem that can bite me in the future (so best if I just remove everything and start over once fixed?).

**Comment by Nikratio** [comment]
Thanks for the report! I haven't had the chance to properly debug this, but I can say for sure that you do not have to worry about silent/creeping corruption. If you run fsck.s3ql, it will identify the file (if any) for which data couldn't be written and move it to /lost+found. In most cases, there will be no loss at all since the block that was written during the crash is still in the local cache and can thus be re-uploaded.

**Comment by Nikratio** [comment]
Looks like the problem may also be a trivial one, could you try the following patch?

```
iff --git a/src/s3ql/backends/gs.py b/src/s3ql/backends/gs.py
index 508e81e..83f4dee 100644
--- a/src/s3ql/backends/gs.py
+++ b/src/s3ql/backends/gs.py
@@ -209,7 +209,8 @@ class Backend(AbstractBackend, metaclass=ABCDocstMeta):
             return True
 
         elif isinstance(exc, AccessTokenExpired):
-            del self.access_token[self.refresh_token]
+            # Delete may fail if multiple threads encounter the same error
+            self.access_token.pop([self.refresh_token, None)
             return True
 
         # Not clear at all what is happening here, but in doubt we retry

```

**Comment by return999** [comment]
I think there is an error in the above patch (unclosed bracket "[").

**Comment by return999** [comment]
I tried the above patch (without "[") and it worked without any errors. Hope it gets applied soon.

**Comment by return999** [comment]
To be more clear, the backup worked, it no longer threw those access key expired errors, so I hope it gets integrated soon in the next release.

**Comment by dgilman** [comment]
I applied the fixed patch and my backup worked successfully. Before, without the patch, any i/o done after the exception would hang forever (typically I'd do an ls or whatever, but it could also be me peeking at rsync to see if it was still writing or blocked). After, I had rsync do all of its copies in around ~24 hours and then s3ql spent the next week or so flushing blocks without error and allowing i/o on the filesystem. So it seems like things picked up quite a bit.
