### ISSUE TITLE
[Invalid Credentials] s3ql.backends.gs.RequestError after a hour

### ISSUE THREAD

**Issue by AntonioIbarraOrtiz** [s3ql/s3ql#84]
Hi, I am new to s3ql. When using google bucket with ADC the mount work but after an hour my mount fail with
```
ls: cannot open directory '.': Transport endpoint is not connected
```
Reading the log the error is **Unauthorized**

The relevant log file is:
```
2019-02-20 18:51:00.053 1467:MainThread s3ql.mount.determine_threads: Using 4 upload threads.
2019-02-20 18:51:00.054 1467:MainThread s3ql.mount.main: Autodetected 1048532 file descriptors available for cache entries
2019-02-20 18:51:00.247 1467:MainThread s3ql.backends.gs._get_access_token: Requesting new access token
2019-02-20 18:51:06.003 1467:MainThread s3ql.mount.get_metadata: Using cached metadata.
2019-02-20 18:51:06.007 1467:MainThread s3ql.mount.main: Setting cache size to 55240 MB
2019-02-20 18:51:06.008 1467:MainThread s3ql.mount.main: Mounting gs://bucket/main at /mnt/bucketmain...
2019-02-20 18:51:06.015 1473:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 1474
2019-02-20 19:55:08.263 1474:Thread-6 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/block_cache.py", line 445, in _upload_loop
    self._do_upload(*tmp)
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/block_cache.py", line 472, in _do_upload
    % obj_id).get_obj_size()
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/backends/common.py", line 279, in perform_write
    return fn(fh)
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/backends/comprenc.py", line 389, in __exit__
    self.close()
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/backends/comprenc.py", line 383, in close
    self.fh.close()
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/backends/comprenc.py", line 548, in close
    self.fh.close()
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/backends/gs.py", line 933, in close
    self.metadata, size=self.obj_size)
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/root/.virtualenvs/s3ql/lib/python3.6/site-packages/s3ql/backends/gs.py", line 485, in write_fh
    raise _map_request_error(exc, key) or exc
s3ql.backends.gs.RequestError: <RequestError, code=401, reason='Unauthorized', message='Invalid Credentials'>
2019-02-20 19:55:08.321 1474:Thread-5 s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2019-02-20 19:55:08.322 1474:Thread-5 root.excepthook: Uncaught top-level exception:
```

Now, I don't understand if is my fault but I exported the

> export GOOGLE_APPLICATION_CREDENTIALS="[PATH]"

and set the credential as ADC and any password like in the documentation http://www.rath.org/s3ql-docs/backends.html

Thanxs

**Comment by andrewchambers** [comment]
This is a related stack trace:
```
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/block_cache.py", line 809, in _get_entry
    el = self.cache[(inode, blockno)]
KeyError: (99040, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/gs.py", line 139, in __call__
    resp = conn.read_response()
  File "/nix/store/h3hbbymlppjkkkiw5c9ybl2103ba1lrw-python3.7-dugong-3.7.4/lib/python3.7/site-packages/dugong/__init__.py", line 774, in read_response
    return eval_coroutine(self.co_read_response(), self.timeout)
  File "/nix/store/h3hbbymlppjkkkiw5c9ybl2103ba1lrw-python3.7-dugong-3.7.4/lib/python3.7/site-packages/dugong/__init__.py", line 1515, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/nix/store/h3hbbymlppjkkkiw5c9ybl2103ba1lrw-python3.7-dugong-3.7.4/lib/python3.7/site-packages/dugong/__init__.py", line 796, in co_read_response
    (status, reason) = yield from self._co_read_status()
  File "/nix/store/h3hbbymlppjkkkiw5c9ybl2103ba1lrw-python3.7-dugong-3.7.4/lib/python3.7/site-packages/dugong/__init__.py", line 918, in _co_read_status
    line = yield from self._co_readstr_until(b'\r\n', MAX_LINE_SIZE)
  File "/nix/store/h3hbbymlppjkkkiw5c9ybl2103ba1lrw-python3.7-dugong-3.7.4/lib/python3.7/site-packages/dugong/__init__.py", line 1314, in _co_readstr_until
    raise ConnectionClosed('server closed connection')
dugong.ConnectionClosed: server closed connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/bin/.mount.s3ql-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/mount.py", line 211, in main
    ret = llfuse.main(workers)
  File "src/fuse_api.pxi", line 330, in llfuse.main
  File "src/handlers.pxi", line 322, in llfuse.fuse_read
  File "src/handlers.pxi", line 323, in llfuse.fuse_read
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/fs.py", line 1041, in read
    tmp = self._readwrite(fh, offset, length=length)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/fs.py", line 1118, in _readwrite
    with self.cache.get(id_, blockno) as fh:
  File "/nix/store/ydk0mfpvn9smcmn72wc9i20slv1d2b79-python3-3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/block_cache.py", line 787, in get
    el = self._get_entry(inode, blockno)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/block_cache.py", line 844, in _get_entry
    backend.perform_read(do_read, 's3ql_data_%d' % obj_id)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/common.py", line 256, in perform_read
    fh = self.open_read(key)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/comprenc.py", line 194, in open_read
    fh = self.backend.open_read(key)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/gs.py", line 378, in open_read
    gs_meta = self._get_gs_meta(key)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/gs.py", line 361, in _get_gs_meta
    resp = self._do_request('GET', path)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/gs.py", line 684, in _do_request
    self._get_access_token()
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/gs.py", line 528, in _get_access_token
    self.adc[0].refresh(self.adc[1])
  File "/nix/store/jawz4sj0iwfl3fcvc2v1nqld17wkj8h1-python3.7-google-auth-1.6.2/lib/python3.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/nix/store/jawz4sj0iwfl3fcvc2v1nqld17wkj8h1-python3.7-google-auth-1.6.2/lib/python3.7/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/nix/store/jawz4sj0iwfl3fcvc2v1nqld17wkj8h1-python3.7-google-auth-1.6.2/lib/python3.7/site-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/nix/store/r73byb664fqllm0da7285bbsvnjspqla-s3ql/lib/python3.7/site-packages/s3ql/backends/gs.py", line 143, in __call__
    raise g_auth.exceptions.TransportError(exc)
google.auth.exceptions.TransportError: server closed connection
```

**Comment by andrewchambers** [comment]
@Nikratio  I think I have found some bugs related to the adc auth token expiry

- The auth requestor pool is not cleaning up disconnected connections.
- Google auth transport errors are not marked as temporary failures.
- Expired tokens are not being removed from the access_token map.
- 401 errors seem to be happening in write_fh where it is not checked for retry.

**Comment by Nikratio** [comment]
Thanks for investigating! Will try to look at the pull request ASAP.

**Comment by andrewchambers** [comment]
@Nikratio the functionality is fixed, just waiting for your stylistic input.

**Comment by Nikratio** [comment]
Thanks! I took a look at it and there's a fix things that I really don't like (eg the new decorator). However, I've not had the time to come up with a good alternative solution so I've not replied yet. I'm trying to find some time for this.

**Comment by andrewchambers** [comment]
No problem, at least the patch can be used as a work around even if it isn't used as is.

**Comment by derobert** [comment]
I'm still seeing invalid credentials (eventually) with the patch from the pull request applied. Note this was during uploading a fair bit of data for a GCE instance via a service account (JSON key). I have threads=2, so I guess that's why it happens twice:

    Mar 13 18:55:00 taniguchi mount.s3ql[1475]: mount.s3ql[1475:Thread-4] root.excepthook: Uncaught top-level exception:
                                                Traceback (most recent call last):
                                                  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
                                                    run_old(*args, **kw)
                                                  File "/usr/lib/python3.5/threading.py", line 862, in run
                                                    self._target(*self._args, **self._kwargs)
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 445, in _upload_loop
                                                    self._do_upload(*tmp)
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 472, in _do_upload
                                                    % obj_id).get_obj_size()
                                                  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
                                                    return method(*a, **kw)
                                                  File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
                                                    return fn(fh)
                                                  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
                                                    self.close()
                                                  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
                                                    self.fh.close()
                                                  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 931, in close
                                                    self.metadata, size=self.obj_size)
                                                  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
                                                    return method(*a, **kw)
                                                  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 162, in wrapped
                                                    raise exc
                                                  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 158, in wrapped
                                                    return method(*a, **kw)
                                                  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 505, in write_fh
                                                    raise _map_request_error(exc, key) or exc
                                                s3ql.backends.common.AuthorizationError: Access denied. Server said: Invalid Credentials
    Mar 13 18:55:00 taniguchi mount.s3ql[1475]: mount.s3ql[1475:Thread-3] s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
    Mar 13 18:55:00 taniguchi mount.s3ql[1475]: mount.s3ql[1475:Thread-3] root.excepthook: Uncaught top-level exception:
                                                Traceback (most recent call last):
                                                  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
                                                    run_old(*args, **kw)
                                                  File "/usr/lib/python3.5/threading.py", line 862, in run
                                                    self._target(*self._args, **self._kwargs)
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 445, in _upload_loop
                                                    self._do_upload(*tmp)
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 472, in _do_upload
                                                    % obj_id).get_obj_size()
                                                  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
                                                    return method(*a, **kw)
                                                  File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
                                                    return fn(fh)
                                                  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
                                                    self.close()
                                                  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
                                                    self.fh.close()
                                                  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 931, in close
                                                    self.metadata, size=self.obj_size)
                                                  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
                                                    return method(*a, **kw)
                                                  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 162, in wrapped
                                                    raise exc
                                                  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 158, in wrapped
                                                    return method(*a, **kw)
                                                  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 505, in write_fh
                                                    raise _map_request_error(exc, key) or exc
                                                s3ql.backends.common.AuthorizationError: Access denied. Server said: Invalid Credentials]
    Mar 13 18:55:04 taniguchi mount.s3ql[1475]: mount.s3ql[1475:CommitThread] s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)

Then, later in the log (and forgive me if I've missed a line or two, it's getting double-logged, probably from both stderr and syslog):

    Mar 13 18:55:04 taniguchi mount.s3ql[1475]: mount.s3ql[1475:CommitThread] root.excepthook: Uncaught top-level exception:
                                                Traceback (most recent call last):
                                                  File "/usr/lib/s3ql/s3ql/database.py", line 143, in get_row
                                                    row = next(res)
                                                StopIteration
                                                
                                                During handling of the above exception, another exception occurred:
                                                
                                                Traceback (most recent call last):
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 590, in upload_if_dirty
                                                    block_id = self.db.get_val('SELECT id FROM blocks WHERE hash=?', (hash_,))
                                                  File "/usr/lib/s3ql/s3ql/database.py", line 127, in get_val
                                                    return self.get_row(*a, **kw)[0]
                                                  File "/usr/lib/s3ql/s3ql/database.py", line 145, in get_row
                                                    raise NoSuchRowError()
                                                s3ql.database.NoSuchRowError: Query produced 0 result rows
                                                
                                                During handling of the above exception, another exception occurred:
                                                
                                                Traceback (most recent call last):
                                                  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
                                                    run_old(*args, **kw)
                                                  File "/usr/lib/s3ql/s3ql/mount.py", line 737, in run
                                                    self.block_cache.upload_if_dirty(el)
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 610, in upload_if_dirty
                                                    self._queue_upload((el, obj_id))
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 655, in _queue_upload
                                                    raise NoWorkerThreads('no upload threads')
                                                s3ql.block_cache.NoWorkerThreads: no upload threads
    Mar 13 18:55:10 taniguchi mount.s3ql[1475]: mount.s3ql[1475:MainThread] s3ql.block_cache.destroy: Unable to flush cache, no upload threads left alive
    Mar 13 18:55:15 taniguchi mount.s3ql[1475]: mount.s3ql[1475:MainThread] s3ql.mount.unmount: Unmounting file system...
    Mar 13 18:55:15 taniguchi mount.s3ql[1475]: mount.s3ql[1475:MainThread] root.excepthook: Uncaught top-level exception:
                                                Traceback (most recent call last):
                                                  File "/usr/lib/s3ql/s3ql/database.py", line 143, in get_row
                                                    row = next(res)
                                                StopIteration
                                                
                                                During handling of the above exception, another exception occurred:
                                                
                                                Traceback (most recent call last):
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 590, in upload_if_dirty
                                                    block_id = self.db.get_val('SELECT id FROM blocks WHERE hash=?', (hash_,))
                                                  File "/usr/lib/s3ql/s3ql/database.py", line 127, in get_val
                                                    return self.get_row(*a, **kw)[0]
                                                  File "/usr/lib/s3ql/s3ql/database.py", line 145, in get_row
                                                    raise NoSuchRowError()
                                                s3ql.database.NoSuchRowError: Query produced 0 result rows
                                                
                                                During handling of the above exception, another exception occurred:
                                                
                                                Traceback (most recent call last):
                                                  File "/usr/bin/mount.s3ql", line 11, in <module>
                                                    load_entry_point('s3ql==3.0', 'console_scripts', 'mount.s3ql')()
                                                  File "/usr/lib/s3ql/s3ql/mount.py", line 211, in main
                                                    ret = llfuse.main(workers)
                                                  File "src/fuse_api.pxi", line 343, in llfuse.main (src/llfuse.c:37283)
                                                  File "src/handlers.pxi", line 577, in llfuse.fuse_setxattr (src/llfuse.c:23023)
                                                  File "src/handlers.pxi", line 590, in llfuse.fuse_setxattr (src/llfuse.c:22940)
                                                  File "/usr/lib/s3ql/s3ql/fs.py", line 240, in setxattr
                                                    self.cache.flush()
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 1011, in flush
                                                    if self.upload_if_dirty(el): # Releases global lock
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 610, in upload_if_dirty
                                                    self._queue_upload((el, obj_id))
                                                  File "/usr/lib/s3ql/s3ql/block_cache.py", line 655, in _queue_upload
                                                    raise NoWorkerThreads('no upload threads')
                                                s3ql.block_cache.NoWorkerThreads: no upload threads
    Mar 13 18:55:19 taniguchi systemd[1]: local-s3ql.service: Main process exited, code=exited, status=1/FAILURE

**Comment by tinmrn** [comment]
Using @andrewchambers ' patch I am also still getting "Access denied. Server said: Invalid Credentials". I was also uploading a whole lot of data, but it does seem to happen after exactly one hour:

```
2019-03-23 15:35:09.146 2987:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 2988
2019-03-23 16:36:04.755 2988:Thread-3 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
.......
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.1-py3.6-linux-x86_64.egg/s3ql/backends/gs.py", line 158, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.1-py3.6-linux-x86_64.egg/s3ql/backends/gs.py", line 505, in write_fh
    raise _map_request_error(exc, key) or exc
s3ql.backends.common.AuthorizationError: Access denied. Server said: Invalid Credentials

```
Let me know if I can do something more to debug it.

**Comment by tinmrn** [comment]
And another time while uploading a lot of data, after ~ 1 hour:

```
2019-03-23 16:50:22.635 4718:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 4719
2019-03-23 17:54:18.867 4719:Thread-4 root.excepthook: Uncaught top-level exception:

```
Then, while not uploading any data at all, it just keeps working:
```
2019-03-23 17:58:02.171 6024:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 6025
2019-03-23 18:59:01.504 6025:fuse-worker-17 s3ql.backends.gs._get_access_token: Requesting new access token

```

**Comment by andrewchambers** [comment]
It sounds like the auth expiry retry is not working correctly while uploading a chunk for some reason. Perhaps the high traffic is causing an error during token refresh.

**Comment by Nikratio** [comment]
I think the core problem here is that `write_fh` is not expecting authentication errors after it has retrieved a `100 continue` response. But I guess this isn't a safe assumption if the upload starts when the token is valid, but finishes once it has expired.

**Comment by Nikratio** [comment]
I think the commit above should fix the issue. Could you please try this version (without the patch from the pull request)? If it still doesn't work, please re-open :-).

**Comment by tinmrn** [comment]
Unfortunately with the current master (c1dd1328) I get a new error (but looks related). I had not uploaded anything on the hour after mounting, but as you can see a bit later. When starting the upload at that moment it crashed right away:

```
2019-03-25 13:26:31.190 22444:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 22445
2019-03-25 15:20:45.313 22445:Thread-15 s3ql.backends.gs._get_access_token: Requesting new access token
2019-03-25 15:20:47.226 22445:Thread-15 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 769, in _removal_loop_simple
    backend.delete('s3ql_data_%d' % id_)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line 289, in delete
    return self.backend.delete(key, force)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/gs.py", line 251, in delete
    resp = self._do_request('DELETE', path)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/gs.py", line 650, in _do_request
    resp = self.conn.read_response()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 764, in read_response
    return eval_coroutine(self.co_read_response(), self.timeout)
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1495, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 780, in co_read_response
    raise StateError('Previous response not read completely')
dugong.StateError: Previous response not read completely
2019-03-25 15:20:49.384 22445:MainThread s3ql.mount.unmount: Unmounting file system...
2019-03-25 15:20:49.447 22445:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.0.2', 'console_scripts', 'mount.s3ql')()
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/mount.py", line 214, in main
    raise RuntimeError('Received signal %d, terminating' % (ret,))
RuntimeError: Received signal 15, terminating
```
Sorry about the version number, I changed that so I could identify my local build.

**Comment by Nikratio** [comment]
Hmm. I can't immediately make sense to me. Does this happen reliably? Could you give me more exact instructions for reproducing it (ideally starting from mkfs.s3ql)?

**Comment by tinmrn** [comment]
Yep, another two times after that:

```
2019-03-25 15:23:13.354 24737:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 24738
2019-03-25 17:25:48.659 24738:Thread-6 s3ql.backends.gs._get_access_token: Requesting new access token
2019-03-25 17:25:50.226 24738:Thread-6 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 769, in _removal_loop_simple
    backend.delete('s3ql_data_%d' % id_)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line 289, in delete
    return self.backend.delete(key, force)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/gs.py", line 251, in delete
    resp = self._do_request('DELETE', path)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/gs.py", line 650, in _do_request
    resp = self.conn.read_response()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 764, in read_response
    return eval_coroutine(self.co_read_response(), self.timeout)
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1495, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 780, in co_read_response
    raise StateError('Previous response not read completely')
dugong.StateError: Previous response not read completely
2019-03-25 17:25:53.466 24738:MainThread s3ql.mount.unmount: Unmounting file system...
2019-03-25 17:25:53.514 24738:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.0.2', 'console_scripts', 'mount.s3ql')()
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/mount.py", line 214, in main
    raise RuntimeError('Received signal %d, terminating' % (ret,))
RuntimeError: Received signal 15, terminating
```

```
2019-03-25 17:27:19.459 26799:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 26800
2019-03-25 18:30:02.030 26800:Thread-14 s3ql.backends.gs._get_access_token: Requesting new access token
2019-03-25 18:30:03.480 26800:Thread-14 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 769, in _removal_loop_simple
    backend.delete('s3ql_data_%d' % id_)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line 289, in delete
    return self.backend.delete(key, force)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/gs.py", line 251, in delete
    resp = self._do_request('DELETE', path)
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/backends/gs.py", line 650, in _do_request
    resp = self.conn.read_response()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 764, in read_response
    return eval_coroutine(self.co_read_response(), self.timeout)
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1495, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 780, in co_read_response
    raise StateError('Previous response not read completely')
dugong.StateError: Previous response not read completely
2019-03-25 18:30:04.645 26800:MainThread s3ql.mount.unmount: Unmounting file system...
2019-03-25 18:30:04.676 26800:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.0.2', 'console_scripts', 'mount.s3ql')()
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.0.2-py3.6-linux-x86_64.egg/s3ql/mount.py", line 214, in main
    raise RuntimeError('Received signal %d, terminating' % (ret,))
RuntimeError: Received signal 15, terminating
```

And then just now something even weirder:

```
2019-03-25 19:22:22.836 29397:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 29398
2019-03-25 20:24:02.706 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 3)...
2019-03-25 20:24:03.157 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 4)...
2019-03-25 20:24:03.544 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 5)...
2019-03-25 20:24:03.584 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 3)...
2019-03-25 20:24:03.830 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 4)...
2019-03-25 20:24:04.141 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 6)...
2019-03-25 20:24:04.210 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 5)...
2019-03-25 20:24:04.894 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 6)...
2019-03-25 20:24:05.043 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 7)...
2019-03-25 20:24:05.914 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 7)...
2019-03-25 20:24:06.886 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 8)...
2019-03-25 20:24:07.616 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 8)...
2019-03-25 20:24:10.282 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 9)...
2019-03-25 20:24:10.849 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 9)...
2019-03-25 20:24:16.005 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 10)...
2019-03-25 20:24:16.795 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 10)...
2019-03-25 20:24:28.806 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 11)...
2019-03-25 20:24:30.584 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 11)...
2019-03-25 20:24:53.128 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 12)...
2019-03-25 20:24:55.951 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 12)...
2019-03-25 20:25:49.164 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 13)...
2019-03-25 20:25:57.729 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 13)...
2019-03-25 20:27:19.355 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 14)...
2019-03-25 20:27:48.744 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 14)...
2019-03-25 20:30:42.702 29398:Thread-3 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 15)...
2019-03-25 20:31:01.352 29398:Thread-4 s3ql.backends.common.wrapped: Encountered AccessTokenExpired (), retrying Backend.write_fh (attempt 15)...
2019-03-25 20:36:18.730 29398:Thread-3 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.write_fh (attempt 16)...
2019-03-25 20:37:50.641 29398:Thread-4 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.write_fh (attempt 16)...
```

I mount it like this:

```
export GOOGLE_APPLICATION_CREDENTIALS="/root/xxx.json"; mount.s3ql --cachedir /mnt/s3ql-cache/s3ql --cachesize 47185920 --allow-other --compress none gs://xxx/ /mnt/cloud
```

I can see if I can reproduce my setup with dummy data later but I need to setup a fresh bucket for that.

**Comment by Nikratio** [comment]
Ah, the last errors do make sense to me. I just pushed a commit to fix them.

I'm still drawing a blank about the state error though. Could you provide logs when running with `--debug-modules dugong,s3ql.backends.gs`?

**Comment by tinmrn** [comment]
https://gist.github.com/tinmrn/f2ef600b3340ad72c0d330dec354aac9

Looks a bit messy, it happens twice with different log context. This morning I did some fscking and mounting but I don't remember the exact times of that. If this is too messy I will do another clean one.

**Comment by Nikratio** [comment]
Another day, another bug found. Thanks for your patience! Could you give it a short again from head?

**Comment by tinmrn** [comment]
Yeah, looks stable now! Awesome, thank you for fixing it.
